In [14]:
import tensorflow as tf
import numpy as np
import time

In [3]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)
print(my_variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [4]:
# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

print(bool_variable)
print(complex_variable)

print("Shape: ", bool_variable.shape)
print("DType: ", bool_variable.dtype)
print("As NumPy: ", bool_variable.numpy())

print("Shape: ", complex_variable.shape)
print("DType: ", complex_variable.dtype)
print("As NumPy: ", complex_variable.numpy())

print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

#diff between normal tensor and as numpy tensor is that normal tensor is a tensor object and as numpy is a numpy array like\
# bject which can be used in numpy functions and operations like slicing, indexing etc. 

# numpy arr example: [1,2,3,4,5,6,7,8,9,10]

# tensor arr example: <tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int32)>


<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>
Shape:  (4,)
DType:  <dtype: 'bool'>
As NumPy:  [False False False  True]
Shape:  (2,)
DType:  <dtype: 'complex128'>
As NumPy:  [5.+4.j 6.+1.j]
Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [6]:
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.math.argmax(my_variable))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)


In [7]:
# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, [1,4]))


Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [11]:
ex_tensor = tf.constant([[10.0, 7.0], [3.0, 2.0], [8.0, 5.0]])
print(tf.reshape(ex_tensor, [1,6]))

tf.Tensor([[10.  7.  3.  2.  8.  5.]], shape=(1, 6), dtype=float32)


In [13]:
ex_array1 = np.array([[10.0, 7.0], [3.0, 2.0], [8.0, 5.0]])
print(np.reshape(ex_array1, (1,6)))

[[10.  7.  3.  2.  8.  5.]]


In [15]:
start_time = time.time()

ex_tensor = tf.constant([[10.0, 7.0], [3.0, 2.0], [8.0, 5.0]])
print(tf.reshape(ex_tensor, [1,6]))

end_time = time.time()

print(f"Time taken: {end_time - start_time} seconds")

tf.Tensor([[10.  7.  3.  2.  8.  5.]], shape=(1, 6), dtype=float32)
Time taken: 0.050559043884277344 seconds


In [16]:
start_time = time.time()

ex_array1 = np.array([[10.0, 7.0], [3.0, 2.0], [8.0, 5.0]])
print(np.reshape(ex_array1, (1,6)))

end_time = time.time()

print(f"Time taken: {end_time - start_time} seconds")

[[10.  7.  3.  2.  8.  5.]]
Time taken: 0.001728057861328125 seconds


In [17]:
a = tf.Variable([2.0, 3.0])
# This will keep the same dtype, float32
a.assign([1, 2]) 
# Not allowed as it resizes the variable: 
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.


In [22]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])
c = tf.Variable(a)
# a and c point to the same object (like pointers)
# a.assign([1, 2])

# a and b are different
print(a.numpy())
print(b.numpy())
print(c.numpy())
# print(a.assign_add([2,3]).numpy())  # [7. 9.]

[5. 6.]
[2. 3.]
[5. 6.]


In [28]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])
c = tf.Variable(a)
# a and c point to the same object (like pointers)
# a.assign([1, 2])

# a and b are different
print(a.numpy())
print(b.numpy())
print(c.numpy())
print(a.assign_add([3,3]).numpy())  # [8. 9.]
print(a.assign_sub([1,1]).numpy())  # [7. 8.]
print(a.assign_mul([2,2]).numpy())  # [14. 16.]

[5. 6.]
[2. 3.]
[5. 6.]
[8. 9.]
[7. 8.]


AttributeError: 'ResourceVariable' object has no attribute 'assign_mul'

In [29]:
# Create a TensorFlow Variable
a = tf.Variable([1, 2])

# Use assign_sub method
print(a.assign_sub([1,1]).numpy()) 

# Use assign_mul method
print(a.assign_mul([2,2]).numpy())

[0 1]


AttributeError: 'ResourceVariable' object has no attribute 'assign_mul'