In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
#creat a tensor with tf.constant()

scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [3]:
#check dim
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([6,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 4], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#create another matrix
matrix2 = tf.constant([[1.,2.],
                        [3.,4.],
                        [5.,6.]], dtype=tf.float16)

matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [9]:
matrix2.ndim

2

In [10]:
matrix3 = tf.constant([[[1,2,3],
                        [4,5,6]]], dtype=tf.float16)
matrix3

<tf.Tensor: shape=(1, 2, 3), dtype=float16, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]]], dtype=float16)>

In [11]:
matrix3.ndim

3

In [12]:
matrix4 = tf.constant([[[[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                         [10,11,12]]]], dtype=tf.float16)
matrix4

<tf.Tensor: shape=(1, 2, 2, 3), dtype=float16, numpy=
array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]]], dtype=float16)>

* Sacalar: a single number
* Vector: a number with direction
* Matrix: a 2-d array of numbers
* Tensor: an n-d array of numbers (where n can be any number, a 0-d tensor is a scalar, a 1-d tensor is a vector)

# TF Variables

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
tensor_changeable = tf.Variable([4,6])
tensor_unchangeable = tf.constant([4,6])
tensor_changeable, tensor_unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>)

In [15]:
tensor_changeable[0] = 6
tensor_changeable

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
tensor_changeable[0].assign(6)
tensor_changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 6], dtype=int32)>

In [17]:
tensor_unchangeable[0] = 6
tensor_unchangeable

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [18]:
tensor_unchangeable[0].assign(6)
tensor_unchangeable

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Random tensors

In [19]:
rand1 = tf.random.Generator.from_seed(32)
rand1 = rand1.normal(shape=(3,2))
rand2 = tf.random.Generator.from_seed(32)
rand2 = rand2.normal(shape=(3,2))
rand1, rand2, rand1 == rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [20]:
rand1 = tf.random.Generator.from_seed(12)
rand1 = rand1.normal(shape=(3,2))
rand2 = tf.random.Generator.from_seed(32) #seed will change the random number
rand2 = rand2.normal(shape=(3,2))

#they are different because they have different seeds
rand1, rand2, rand1 == rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

## Shuffel Oder of the data (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)

In [22]:
shuf_not = tf.constant([[10,7],
                        [3,4],
                        [2,5]])
#shuf_not.ndim #ans: 2
shuf_not

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [23]:
#shuffle 1st the tensor
tf.random.shuffle(shuf_not)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [24]:
#shuffle 2nd the tensor
tf.random.shuffle(shuf_not)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [25]:
#shuffle 3rd the tensor
tf.random.shuffle(shuf_not , seed=42) #this seed is operation level seed is not global seed, 
# so it will not effect other operation, but it will effect the operation, for reproducibility

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [27]:
#shuffle the tensor
tf.random.set_seed(42) #global level seed which will not change the order of the tensor in the operation level seed 
tf.random.shuffle(shuf_not, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other way to create tensors

In [28]:
tf.ones([4,6])

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [29]:
tf.zeros([4,6])

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [30]:
tf.twos([4,6])

AttributeError: module 'tensorflow' has no attribute 'twos'

In [32]:
# turn numpy array into tensor 
import numpy as np
numpy_A = np.arange(1,31, dtype=np.int32)
 
#x = tf.constant(some_matrix) #capital for matrix or tensor
x = tf.constant(numpy_A, shape=(3,10))
#y = tf.constant(vector) #non capital for vector
y = tf.constant(numpy_A, shape=(10,3))

z = tf.constant(numpy_A, shape=(3,2,5))

numpy_A, x, y, z

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32),
 <tf.Tensor: shape=(3, 10), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]], dtype=int32)>,
 <tf.Tensor: shape=(10, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],
 
        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],
 
        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]], dtype=int32)>)

## Getting info from tensors

In [34]:
# Create a tensor of rank 4
rank_4_tensor = tf.zeros([8, 5, 3, 4])
rank_4_tensor


<tf.Tensor: shape=(8, 5, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
  

In [35]:
rank_4_tensor[0]

<tf.Tensor: shape=(5, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [36]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([8, 5, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=480>)

In [37]:
8 * 5 * 3 * 4

480

In [39]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (8*5*3*4):", tf.size(rank_4_tensor))
print("Total number of elements (8*5*3*4):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (8, 5, 3, 4)
Elements along axis 0 of tensor: 8
Elements along last axis of tensor: 4
Total number of elements (8*5*3*4): tf.Tensor(480, shape=(), dtype=int32)
Total number of elements (8*5*3*4): 480


## Indexing tensors

In [41]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [40]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [44]:
rank_2_tensor = tf.constant([[6,4],
                             [10,11]])

rank_2_tensor.shape, rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [45]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 4, 11], dtype=int32)>

In [46]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 6],
        [ 4]],

       [[10],
        [11]]], dtype=int32)>

In [47]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 6],
        [ 4]],

       [[10],
        [11]]], dtype=int32)>

In [48]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 6,  4]],

       [[10, 11]]], dtype=int32)>