In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [3]:
#creat a tensor with tf.constant()

scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [4]:
#check dim
scalar.ndim

0

In [7]:
#create a vector
vector = tf.constant([6,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 4], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
#create a matrix
matrix = tf.constant([[1,2],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
#create another matrix
matrix2 = tf.constant([[1.,2.],
                        [3.,4.],
                        [5.,6.]], dtype=tf.float16)

matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [12]:
matrix2.ndim

2

In [15]:
matrix3 = tf.constant([[[1,2,3],
                        [4,5,6]]], dtype=tf.float16)
matrix3

<tf.Tensor: shape=(1, 2, 3), dtype=float16, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]]], dtype=float16)>

In [16]:
matrix3.ndim

3

In [17]:
matrix4 = tf.constant([[[[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                         [10,11,12]]]], dtype=tf.float16)
matrix4

<tf.Tensor: shape=(1, 2, 2, 3), dtype=float16, numpy=
array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]]], dtype=float16)>

* Sacalar: a single number
* Vector: a number with direction
* Matrix: a 2-d array of numbers
* Tensor: an n-d array of numbers (where n can be any number, a 0-d tensor is a scalar, a 1-d tensor is a vector)

# TF Variables

In [19]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [22]:
tensor_changeable = tf.Variable([4,6])
tensor_unchangeable = tf.constant([4,6])
tensor_changeable, tensor_unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>)

In [24]:
tensor_changeable[0] = 6
tensor_changeable

TypeError: 'ResourceVariable' object does not support item assignment

In [25]:
tensor_changeable[0].assign(6)
tensor_changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 6], dtype=int32)>

In [26]:
tensor_unchangeable[0] = 6
tensor_unchangeable

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [27]:
tensor_unchangeable[0].assign(6)
tensor_unchangeable

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Random tensors

In [33]:
rand1 = tf.random.Generator.from_seed(32)
rand1 = rand1.normal(shape=(3,2))
rand2 = tf.random.Generator.from_seed(32)
rand2 = rand2.normal(shape=(3,2))
rand1, rand2, rand1 == rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [34]:
rand1 = tf.random.Generator.from_seed(12)
rand1 = rand1.normal(shape=(3,2))
rand2 = tf.random.Generator.from_seed(32)
rand2 = rand2.normal(shape=(3,2))
rand1, rand2, rand1 == rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)